### ISSUE TITLE
Add Taezars

### ISSUE THREAD

**Issue by uid2532** [tezosweb/tezos-ecosystem-projects#86]
Please, add taezars.md and taezars.jpeg.

**Comment by uid2532** [comment]
![taezars](https://user-images.githubusercontent.com/54663233/192634760-37025997-ba19-4433-a331-d23d25819328.jpeg)
[taezars.md](https://github.com/tezosweb/tezos-ecosystem-projects/files/9659593/taezars.md)

**Comment by tezoslibrarian** [comment]
Please see the instructions for adding a Github Pull Request.
Regards,
Tezos Support
